# Name your project
name: 'healthcare_analytics'
version: '1.0.0'
config-version: 2

# These folders define where dbt looks for files
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # compiled SQL files
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  healthcare_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
